language: java
jdk:
- openjdk8
services:
- docker
install:
- bash scripts/install.sh
- bash scripts/build.sh rmspogfo
script:
- mvn test
- bash scripts/coveralls.sh
after_success:
- bash scripts/tag.sh
after_deploy:
- bash scripts/gitbook.sh
branches:
  except:
  - "/^v[0-9]+\\.[0-9]+\\.[0-9]+.*/"
