language: java
jdk:
- openjdk8
services:
- docker
before_script:
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/

install:
- bash scripts/install.sh
- bash scripts/build.sh rmspogfo
script:
- mvn test
- mvn clean install -DskipTests
- docker build -t bwerquin/pogues-bo .
after_success:
- bash scripts/tag.sh
deploy:
  - skip_cleanup: true
    provider: script
    script:
      echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      && docker push bwerquin/pogues-bo
    on:
      branch: master

  - skip_cleanup: true
    provider: script
    script: kubectl --token $K8S_TOKEN --server $K8S_SERVER --insecure-skip-tls-verify rollout restart deployment/pogues-bo -n pogues-eno
    on:
      branch: master
after_deploy:
- bash scripts/gitbook.sh
branches:
  except:
  - "/^v[0-9]+\\.[0-9]+\\.[0-9]+.*/"
